import { Inter } from "next/font/google";
import "../globals.css";
import { isSuperAdmin } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  balance,
  expenses,
  profit,
  customers
}) {
  const superAdmin = isSuperAdmin();
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {children}
        <div className="flex flex-initial gap-5 mx-auto">
        {balance}
        {expenses}
        {profit}
        </div>
        {superAdmin && <div>{customers}</div>}
      </body>
    </html>
  );
}
